In [8]:
import numpy as np
import pandas as pd

from perceptron_from_scratch import Perceptron

In [9]:
df = pd.read_csv("../../../../../data/classification/and_gate_datasets.csv")
print(df)

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1


In [10]:
data = df.to_numpy()
data

array([[0, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 1, 1]])

In [11]:
X_train = data[:, :-1]
y_train = data[:, -1]
X_train, y_train 

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 0, 0, 1]))

In [12]:
n_samples, n_features = X_train.shape
n_samples, n_features

(4, 2)

In [13]:
perceptron = Perceptron(input_size=n_features, learning_rate=0.1)
# perceptron.weights = np.array([-0.5, 0.4, 1])
print(perceptron.weights)
perceptron.train(X_train, y_train, epochs=100)

[0.43869579 0.77288642 0.10600958]
Converged at epoch 9 and weight [-0.46130421  0.27288642  0.20600958]


In [14]:
new_record = np.array([0,1])
prediction = perceptron.predict(new_record)
print("Prediction:", prediction)

Prediction: 0
